### PR TITLE
LEST-NONE - Make `packages/docs` a ES module.

### PR DESCRIPTION
**Pull request by yogwoggf**
## Changes

Added `type: "module"` to packages/docs/package.json.
This is required so certain ESM packages (like luals-annotations) can properly import it. The docs have javascript which uses ESM but has no marker, so Node gets confused and spews abominable errors.

## Impact

Anyone importing the index.js files from the docs will now be able to if they're using ESM. They'll also get a correct error if they're using CJS.

## Helpful Links

[API Docs](https://taservers.github.io/lest/docs/api/expect)

[Project Board](https://taservers.atlassian.net/jira/software/c/projects/LEST/boards/4)

[Discord](https://discord.tasevers.com)

### CODE REVIEW

**Comment by yogwoggf** [comment]
I'm at a loss for words. I HAVE TRIED THIS ON 3 DIFFERENT NODE VERSIONS. NODE 20 IS KNOWN NOT TO WORK WITH TS-NODE. NODE 18 WANTS TYPE: MODULE. NODE 16 WANTS TYPE: MODULE. BUT DOCUSAURUS COMPLETELY DOES NOT WORK WITH ESM. WTF???

**Comment by yogwoggf** [comment]
Please. Fix this. @Derpius. You are the one who made the docs package. Please.

**Comment by Derpius** [comment]
@yogwoggf I'm assuming this PR just wants closing then, given it's not working with Docusaurus? I'll open a ticket to convert the docs repo to TypeScript

**Comment by yogwoggf** [comment]
Yes ok .

**Pull request closed without merging**
